"""
ICU Drug Database — hardcoded from public medical/pharmacological knowledge.
No external API or license required. All data is standard clinical reference.
"""

DRUG_DB = {
    "warfarin": {
        "class": "anticoagulant",
        "typical_dose_mg_kg": None,
        "fixed_dose_mg": 5.0,
        "max_dose_mg": 10.0,
        "renal_adjustment": False,
        "indications": ["atrial fibrillation", "dvt", "pe", "mechanical heart valve"],
    },
    "heparin": {
        "class": "anticoagulant",
        "typical_dose_mg_kg": None,
        "fixed_dose_units_kg": 80,
        "max_dose_units": 10000,
        "renal_adjustment": False,
        "indications": ["dvt", "pe", "acs"],
    },
    "aspirin": {
        "class": "antiplatelet",
        "typical_dose_mg_kg": None,
        "fixed_dose_mg": 81.0,
        "max_dose_mg": 325.0,
        "renal_adjustment": True,
        "indications": ["acs", "stroke prevention", "pain"],
    },
    "metformin": {
        "class": "antidiabetic",
        "typical_dose_mg_kg": None,
        "fixed_dose_mg": 500.0,
        "max_dose_mg": 2000.0,
        "renal_adjustment": True,
        "indications": ["type 2 diabetes"],
    },
    "insulin_regular": {
        "class": "antidiabetic",
        "typical_dose_units_kg": 0.1,
        "max_dose_units_kg": 0.3,
        "renal_adjustment": True,
        "indications": ["hyperglycemia", "dka", "type 1 diabetes"],
    },
    "norepinephrine": {
        "class": "vasopressor",
        "typical_dose_mcg_kg_min": 0.1,
        "max_dose_mcg_kg_min": 3.0,
        "renal_adjustment": False,
        "indications": ["septic shock", "hypotension"],
    },
    "dopamine": {
        "class": "vasopressor",
        "typical_dose_mcg_kg_min": 5.0,
        "max_dose_mcg_kg_min": 20.0,
        "renal_adjustment": False,
        "indications": ["cardiogenic shock", "hypotension"],
    },
    "vancomycin": {
        "class": "antibiotic",
        "typical_dose_mg_kg": 15.0,
        "max_dose_mg_kg": 25.0,
        "renal_adjustment": True,
        "indications": ["mrsa", "gram positive infections"],
    },
    "piperacillin_tazobactam": {
        "class": "antibiotic",
        "typical_dose_mg_kg": 100.0,
        "max_dose_mg_kg": 400.0,
        "renal_adjustment": True,
        "indications": ["gram negative infections", "sepsis"],
    },
    "ciprofloxacin": {
        "class": "antibiotic",
        "typical_dose_mg_kg": None,
        "fixed_dose_mg": 400.0,
        "max_dose_mg": 800.0,
        "renal_adjustment": True,
        "indications": ["uti", "gram negative infections"],
    },
    "metronidazole": {
        "class": "antibiotic",
        "typical_dose_mg_kg": None,
        "fixed_dose_mg": 500.0,
        "max_dose_mg": 1500.0,
        "renal_adjustment": False,
        "indications": ["anaerobic infections", "c diff"],
    },
    "furosemide": {
        "class": "diuretic",
        "typical_dose_mg_kg": 0.5,
        "max_dose_mg_kg": 2.0,
        "renal_adjustment": True,
        "indications": ["fluid overload", "heart failure", "edema"],
    },
    "propofol": {
        "class": "sedative",
        "typical_dose_mcg_kg_min": 25.0,
        "max_dose_mcg_kg_min": 75.0,
        "renal_adjustment": False,
        "indications": ["sedation", "procedural anesthesia"],
    },
    "midazolam": {
        "class": "sedative",
        "typical_dose_mg_kg": 0.02,
        "max_dose_mg_kg": 0.1,
        "renal_adjustment": True,
        "indications": ["sedation", "anxiety", "seizure"],
    },
    "fentanyl": {
        "class": "opioid",
        "typical_dose_mcg_kg_hr": 25.0,
        "max_dose_mcg_kg_hr": 200.0,
        "renal_adjustment": True,
        "indications": ["pain", "sedation"],
    },
    "morphine": {
        "class": "opioid",
        "typical_dose_mg_kg": 0.05,
        "max_dose_mg_kg": 0.1,
        "renal_adjustment": True,
        "indications": ["pain", "dyspnea"],
    },
    "lisinopril": {
        "class": "ace_inhibitor",
        "typical_dose_mg_kg": None,
        "fixed_dose_mg": 10.0,
        "max_dose_mg": 40.0,
        "renal_adjustment": True,
        "indications": ["hypertension", "heart failure"],
    },
    "metoprolol": {
        "class": "beta_blocker",
        "typical_dose_mg_kg": None,
        "fixed_dose_mg": 25.0,
        "max_dose_mg": 200.0,
        "renal_adjustment": False,
        "indications": ["hypertension", "heart failure", "atrial fibrillation"],
    },
    "amiodarone": {
        "class": "antiarrhythmic",
        "typical_dose_mg_kg": None,
        "fixed_dose_mg": 200.0,
        "max_dose_mg": 400.0,
        "renal_adjustment": False,
        "indications": ["atrial fibrillation", "ventricular tachycardia"],
    },
    "digoxin": {
        "class": "cardiac_glycoside",
        "typical_dose_mg_kg": None,
        "fixed_dose_mg": 0.25,
        "max_dose_mg": 0.5,
        "renal_adjustment": True,
        "indications": ["atrial fibrillation", "heart failure"],
    },
    "clopidogrel": {
        "class": "antiplatelet",
        "typical_dose_mg_kg": None,
        "fixed_dose_mg": 75.0,
        "max_dose_mg": 300.0,
        "renal_adjustment": False,
        "indications": ["acs", "stroke prevention", "stent"],
    },
    "phenytoin": {
        "class": "anticonvulsant",
        "typical_dose_mg_kg": 5.0,
        "max_dose_mg_kg": 20.0,
        "renal_adjustment": False,
        "indications": ["seizure", "epilepsy"],
    },
    "levetiracetam": {
        "class": "anticonvulsant",
        "typical_dose_mg_kg": None,
        "fixed_dose_mg": 500.0,
        "max_dose_mg": 3000.0,
        "renal_adjustment": True,
        "indications": ["seizure", "epilepsy"],
    },
    "dexamethasone": {
        "class": "corticosteroid",
        "typical_dose_mg_kg": 0.1,
        "max_dose_mg_kg": 0.5,
        "renal_adjustment": False,
        "indications": ["inflammation", "covid", "cerebral edema", "septic shock"],
    },
    "hydrocortisone": {
        "class": "corticosteroid",
        "typical_dose_mg_kg": None,
        "fixed_dose_mg": 50.0,
        "max_dose_mg": 200.0,
        "renal_adjustment": False,
        "indications": ["adrenal insufficiency", "septic shock"],
    },
    "pantoprazole": {
        "class": "ppi",
        "typical_dose_mg_kg": None,
        "fixed_dose_mg": 40.0,
        "max_dose_mg": 80.0,
        "renal_adjustment": False,
        "indications": ["gi prophylaxis", "gerd", "peptic ulcer"],
    },
    "ondansetron": {
        "class": "antiemetic",
        "typical_dose_mg_kg": 0.1,
        "max_dose_mg_kg": 0.15,
        "renal_adjustment": False,
        "indications": ["nausea", "vomiting"],
    },
    "acetaminophen": {
        "class": "analgesic",
        "typical_dose_mg_kg": 15.0,
        "max_dose_mg_kg": 15.0,
        "max_daily_mg": 4000.0,
        "renal_adjustment": False,
        "indications": ["pain", "fever"],
    },
    "ibuprofen": {
        "class": "nsaid",
        "typical_dose_mg_kg": 10.0,
        "max_dose_mg_kg": 10.0,
        "renal_adjustment": True,
        "indications": ["pain", "fever", "inflammation"],
    },
    "ketorolac": {
        "class": "nsaid",
        "typical_dose_mg_kg": None,
        "fixed_dose_mg": 30.0,
        "max_dose_mg": 30.0,
        "renal_adjustment": True,
        "indications": ["pain", "inflammation"],
    },
    "lorazepam": {
        "class": "benzodiazepine",
        "typical_dose_mg_kg": 0.02,
        "max_dose_mg_kg": 0.05,
        "renal_adjustment": False,
        "indications": ["anxiety", "sedation", "alcohol withdrawal", "seizure"],
    },
    "haloperidol": {
        "class": "antipsychotic",
        "typical_dose_mg_kg": None,
        "fixed_dose_mg": 2.0,
        "max_dose_mg": 10.0,
        "renal_adjustment": False,
        "indications": ["delirium", "agitation", "psychosis"],
    },
    "quetiapine": {
        "class": "antipsychotic",
        "typical_dose_mg_kg": None,
        "fixed_dose_mg": 25.0,
        "max_dose_mg": 200.0,
        "renal_adjustment": False,
        "indications": ["delirium", "agitation", "psychosis"],
    },
    "atenolol": {
        "class": "beta_blocker",
        "typical_dose_mg_kg": None,
        "fixed_dose_mg": 50.0,
        "max_dose_mg": 100.0,
        "renal_adjustment": True,
        "indications": ["hypertension", "angina"],
    },
    "amlodipine": {
        "class": "calcium_channel_blocker",
        "typical_dose_mg_kg": None,
        "fixed_dose_mg": 5.0,
        "max_dose_mg": 10.0,
        "renal_adjustment": False,
        "indications": ["hypertension", "angina"],
    },
    "diltiazem": {
        "class": "calcium_channel_blocker",
        "typical_dose_mg_kg": None,
        "fixed_dose_mg": 30.0,
        "max_dose_mg": 360.0,
        "renal_adjustment": False,
        "indications": ["atrial fibrillation", "hypertension", "angina"],
    },
    "simvastatin": {
        "class": "statin",
        "typical_dose_mg_kg": None,
        "fixed_dose_mg": 20.0,
        "max_dose_mg": 80.0,
        "renal_adjustment": False,
        "indications": ["hyperlipidemia", "cardiovascular prevention"],
    },
    "atorvastatin": {
        "class": "statin",
        "typical_dose_mg_kg": None,
        "fixed_dose_mg": 40.0,
        "max_dose_mg": 80.0,
        "renal_adjustment": False,
        "indications": ["hyperlipidemia", "cardiovascular prevention"],
    },
    "fluconazole": {
        "class": "antifungal",
        "typical_dose_mg_kg": 6.0,
        "max_dose_mg_kg": 12.0,
        "renal_adjustment": True,
        "indications": ["candida", "fungal infection"],
    },
    "acyclovir": {
        "class": "antiviral",
        "typical_dose_mg_kg": 5.0,
        "max_dose_mg_kg": 10.0,
        "renal_adjustment": True,
        "indications": ["herpes", "hsv encephalitis", "vzv"],
    },
    "phenobarbital": {
        "class": "anticonvulsant",
        "typical_dose_mg_kg": 1.0,
        "max_dose_mg_kg": 3.0,
        "renal_adjustment": False,
        "indications": ["seizure", "status epilepticus", "alcohol withdrawal"],
    },
    "naloxone": {
        "class": "opioid_antagonist",
        "typical_dose_mg_kg": 0.01,
        "max_dose_mg_kg": 0.1,
        "renal_adjustment": False,
        "indications": ["opioid reversal", "overdose"],
    },
    "flumazenil": {
        "class": "benzodiazepine_antagonist",
        "typical_dose_mg_kg": None,
        "fixed_dose_mg": 0.2,
        "max_dose_mg": 1.0,
        "renal_adjustment": False,
        "indications": ["benzodiazepine reversal"],
    },
    "vitamin_k": {
        "class": "coagulation_factor",
        "typical_dose_mg_kg": None,
        "fixed_dose_mg": 10.0,
        "max_dose_mg": 10.0,
        "renal_adjustment": False,
        "indications": ["warfarin reversal", "coagulopathy"],
    },
    "protamine": {
        "class": "heparin_antagonist",
        "typical_dose_mg_per_100units_heparin": 1.0,
        "renal_adjustment": False,
        "indications": ["heparin reversal"],
    },
    "epinephrine": {
        "class": "vasopressor",
        "typical_dose_mcg_kg_min": 0.05,
        "max_dose_mcg_kg_min": 1.0,
        "renal_adjustment": False,
        "indications": ["anaphylaxis", "cardiac arrest", "severe asthma"],
    },
    "vasopressin": {
        "class": "vasopressor",
        "typical_dose_units_min": 0.03,
        "max_dose_units_min": 0.04,
        "renal_adjustment": False,
        "indications": ["septic shock", "refractory hypotension"],
    },
    "potassium_chloride": {
        "class": "electrolyte",
        "typical_dose_meq_hr": 10.0,
        "max_dose_meq_hr": 20.0,
        "renal_adjustment": True,
        "indications": ["hypokalemia"],
    },
    "magnesium_sulfate": {
        "class": "electrolyte",
        "typical_dose_g": 2.0,
        "max_dose_g": 6.0,
        "renal_adjustment": True,
        "indications": ["hypomagnesemia", "eclampsia", "torsades"],
    },
    "sodium_bicarbonate": {
        "class": "buffer",
        "typical_dose_meq_kg": 1.0,
        "max_dose_meq_kg": 2.0,
        "renal_adjustment": False,
        "indications": ["metabolic acidosis", "hyperkalemia"],
    },
}

DANGEROUS_INTERACTIONS = {
    ("warfarin", "aspirin"): {
        "severity": "major",
        "effect": "Markedly increased bleeding risk — additive anticoagulation",
        "mechanism": "Warfarin anticoagulation + aspirin platelet inhibition",
        "recommendation": "avoid_combination",
        "safe_alternative": "acetaminophen for pain instead of aspirin",
    },
    ("warfarin", "ibuprofen"): {
        "severity": "major",
        "effect": "Severe bleeding risk — NSAIDs increase warfarin levels",
        "mechanism": "NSAID displaces warfarin from protein binding",
        "recommendation": "avoid_combination",
        "safe_alternative": "acetaminophen for pain",
    },
    ("warfarin", "ciprofloxacin"): {
        "severity": "major",
        "effect": "Dramatically increased INR — bleeding risk",
        "mechanism": "Ciprofloxacin inhibits warfarin metabolism via CYP1A2",
        "recommendation": "monitor_inr_closely",
        "safe_alternative": "amoxicillin if spectrum allows",
    },
    ("warfarin", "fluconazole"): {
        "severity": "major",
        "effect": "Severe INR elevation — bleeding",
        "mechanism": "Fluconazole is strong CYP2C9 inhibitor — warfarin not metabolized",
        "recommendation": "reduce_warfarin_dose_by_50_percent",
        "safe_alternative": "anidulafungin (no CYP interaction)",
    },
    ("warfarin", "metronidazole"): {
        "severity": "major",
        "effect": "INR doubles or triples — major bleeding risk",
        "mechanism": "Metronidazole inhibits CYP2C9 and CYP3A4",
        "recommendation": "reduce_warfarin_dose_monitor_inr",
        "safe_alternative": "tinidazole with close monitoring",
    },
    ("warfarin", "amiodarone"): {
        "severity": "major",
        "effect": "Potentiates warfarin significantly — supratherapeutic INR",
        "mechanism": "Amiodarone inhibits CYP2C9 — warfarin accumulates",
        "recommendation": "reduce_warfarin_by_30_to_50_percent",
        "safe_alternative": "no good alternative — must monitor INR weekly",
    },
    ("metformin", "contrast_dye"): {
        "severity": "major",
        "effect": "Lactic acidosis — can be fatal",
        "mechanism": "Contrast dye causes transient renal failure — metformin accumulates",
        "recommendation": "hold_metformin_48h_before_contrast",
        "safe_alternative": "insulin for glucose control perioperatively",
    },
    ("ssri", "maoi"): {
        "severity": "contraindicated",
        "effect": "Serotonin syndrome — potentially fatal: hyperthermia, seizures, death",
        "mechanism": "Combined serotonergic effects overwhelm 5-HT regulation",
        "recommendation": "never_combine_require_14_day_washout",
        "safe_alternative": "use only one class at a time",
    },
    ("fluoxetine", "maoi"): {
        "severity": "contraindicated",
        "effect": "Serotonin syndrome — FATAL",
        "mechanism": "Fluoxetine has 5-week half-life — long washout needed",
        "recommendation": "5_week_washout_before_maoi",
        "safe_alternative": "other SSRI with shorter half-life if switching needed",
    },
    ("ciprofloxacin", "haloperidol"): {
        "severity": "major",
        "effect": "QT prolongation — fatal arrhythmia (Torsades de Pointes)",
        "mechanism": "Both drugs prolong QT interval additively",
        "recommendation": "avoid_combination_monitor_ecg",
        "safe_alternative": "metronidazole instead of ciprofloxacin",
    },
    ("haloperidol", "amiodarone"): {
        "severity": "major",
        "effect": "Additive QT prolongation — Torsades de Pointes risk",
        "mechanism": "Both are potent QT prolongers",
        "recommendation": "avoid_combination",
        "safe_alternative": "quetiapine at low dose for delirium",
    },
    ("ondansetron", "haloperidol"): {
        "severity": "major",
        "effect": "QT prolongation — fatal arrhythmia",
        "mechanism": "Both drugs block hERG potassium channel",
        "recommendation": "avoid_combination",
        "safe_alternative": "prochlorperazine for nausea",
    },
    ("piperacillin_tazobactam", "vancomycin"): {
        "severity": "moderate",
        "effect": "Acute kidney injury — nephrotoxicity significantly increased",
        "mechanism": "Combined nephrotoxic effect on renal tubules",
        "recommendation": "monitor_renal_function_daily",
        "safe_alternative": "meropenem instead of pip-tazo if renal function declining",
    },
    ("vancomycin", "furosemide"): {
        "severity": "moderate",
        "effect": "Nephrotoxicity and ototoxicity — increased vancomycin levels",
        "mechanism": "Furosemide reduces renal clearance of vancomycin",
        "recommendation": "monitor_vancomycin_levels_and_creatinine",
        "safe_alternative": "minimize furosemide dose; consider alternative diuretic",
    },
    ("vancomycin", "aminoglycoside"): {
        "severity": "major",
        "effect": "Severe nephrotoxicity",
        "mechanism": "Both drugs are nephrotoxic — synergistic damage",
        "recommendation": "avoid_concurrent_use",
        "safe_alternative": "use one agent only",
    },
    ("lisinopril", "potassium_chloride"): {
        "severity": "major",
        "effect": "Dangerous hyperkalemia — cardiac arrest",
        "mechanism": "ACE inhibitors retain potassium; supplementation adds to it",
        "recommendation": "monitor_potassium_closely",
        "safe_alternative": "reduce KCl supplementation; check K levels first",
    },
    ("lisinopril", "spironolactone"): {
        "severity": "major",
        "effect": "Life-threatening hyperkalemia",
        "mechanism": "Both agents reduce potassium excretion synergistically",
        "recommendation": "monitor_potassium_weekly",
        "safe_alternative": "furosemide instead of spironolactone",
    },
    ("metoprolol", "diltiazem"): {
        "severity": "major",
        "effect": "Severe bradycardia and heart block",
        "mechanism": "Both drugs slow AV node conduction additively",
        "recommendation": "avoid_combination",
        "safe_alternative": "use only one rate-control agent",
    },
    ("metoprolol", "verapamil"): {
        "severity": "major",
        "effect": "Complete heart block — cardiac arrest",
        "mechanism": "Synergistic AV node suppression",
        "recommendation": "contraindicated_in_most_cases",
        "safe_alternative": "amiodarone for rate control if needed",
    },
    ("phenytoin", "warfarin"): {
        "severity": "major",
        "effect": "Erratic INR — initially increases then decreases warfarin effect",
        "mechanism": "Phenytoin induces CYP2C9 — complex bidirectional interaction",
        "recommendation": "monitor_inr_very_closely",
        "safe_alternative": "levetiracetam (no CYP interactions)",
    },
    ("phenytoin", "ciprofloxacin"): {
        "severity": "moderate",
        "effect": "Increased phenytoin toxicity",
        "mechanism": "Ciprofloxacin inhibits phenytoin metabolism",
        "recommendation": "monitor_phenytoin_levels",
        "safe_alternative": "use different antibiotic",
    },
    ("simvastatin", "amiodarone"): {
        "severity": "major",
        "effect": "Severe rhabdomyolysis — muscle breakdown, renal failure",
        "mechanism": "Amiodarone inhibits CYP3A4 — simvastatin accumulates",
        "recommendation": "do_not_exceed_20mg_simvastatin",
        "safe_alternative": "switch to rosuvastatin (not CYP3A4 metabolized)",
    },
    ("simvastatin", "fluconazole"): {
        "severity": "major",
        "effect": "Rhabdomyolysis",
        "mechanism": "Strong CYP3A4 inhibition causes simvastatin accumulation",
        "recommendation": "hold_simvastatin_during_fluconazole_course",
        "safe_alternative": "rosuvastatin or pravastatin",
    },
    ("aspirin", "ibuprofen"): {
        "severity": "moderate",
        "effect": "Ibuprofen blocks aspirin's antiplatelet effect",
        "mechanism": "Ibuprofen competitively inhibits COX-1 binding site",
        "recommendation": "take_aspirin_2h_before_ibuprofen",
        "safe_alternative": "acetaminophen instead of ibuprofen",
    },
    ("clopidogrel", "omeprazole"): {
        "severity": "major",
        "effect": "Reduced antiplatelet effect — stent thrombosis risk",
        "mechanism": "Omeprazole inhibits CYP2C19 — clopidogrel not activated",
        "recommendation": "switch_to_pantoprazole",
        "safe_alternative": "pantoprazole (minimal CYP2C19 inhibition)",
    },
    ("clopidogrel", "aspirin"): {
        "severity": "moderate",
        "effect": "Increased bleeding risk (dual antiplatelet therapy)",
        "mechanism": "Both inhibit platelet aggregation via different mechanisms",
        "recommendation": "use_only_when_clinically_indicated_eg_acs_stent",
        "safe_alternative": "monotherapy if dual therapy not indicated",
    },
    ("fentanyl", "midazolam"): {
        "severity": "major",
        "effect": "Respiratory depression — apnea",
        "mechanism": "Synergistic CNS and respiratory depression",
        "recommendation": "reduce_doses_of_both_monitor_closely",
        "safe_alternative": "use one agent; have naloxone and flumazenil ready",
    },
    ("fentanyl", "lorazepam"): {
        "severity": "major",
        "effect": "Respiratory depression — potentially fatal",
        "mechanism": "Opioid + benzodiazepine synergistic respiratory suppression",
        "recommendation": "extreme_caution_reduce_doses",
        "safe_alternative": "one sedative class only if possible",
    },
    ("morphine", "midazolam"): {
        "severity": "major",
        "effect": "Severe respiratory depression",
        "mechanism": "Synergistic CNS depression",
        "recommendation": "monitor_closely_have_reversal_agents_ready",
        "safe_alternative": "use lowest effective doses of each",
    },
    ("naloxone", "morphine"): {
        "severity": "moderate",
        "effect": "Precipitates acute opioid withdrawal — agitation, hypertension",
        "mechanism": "Naloxone rapidly displaces morphine from mu receptors",
        "recommendation": "use_only_for_overdose_reversal",
        "safe_alternative": "titrate naloxone carefully to avoid full reversal",
    },
    ("furosemide", "aminoglycoside"): {
        "severity": "major",
        "effect": "Severe ototoxicity — permanent hearing loss",
        "mechanism": "Both drugs damage cochlear hair cells synergistically",
        "recommendation": "avoid_concurrent_use",
        "safe_alternative": "alternative diuretic; alternative antibiotic",
    },
    ("furosemide", "digoxin"): {
        "severity": "major",
        "effect": "Digoxin toxicity — hypokalemia worsens toxicity",
        "mechanism": "Furosemide causes hypokalemia which sensitizes heart to digoxin",
        "recommendation": "replace_potassium_aggressively",
        "safe_alternative": "monitor potassium and digoxin levels closely",
    },
    ("digoxin", "amiodarone"): {
        "severity": "major",
        "effect": "Severe digoxin toxicity — bradycardia, heart block, death",
        "mechanism": "Amiodarone doubles digoxin levels by reducing renal clearance",
        "recommendation": "reduce_digoxin_by_50_percent",
        "safe_alternative": "consider stopping digoxin if amiodarone started",
    },
    ("digoxin", "diltiazem"): {
        "severity": "moderate",
        "effect": "Elevated digoxin levels — toxicity",
        "mechanism": "Diltiazem reduces renal and non-renal digoxin clearance",
        "recommendation": "monitor_digoxin_levels",
        "safe_alternative": "beta-blocker for rate control instead of diltiazem",
    },
    ("dexamethasone", "insulin_regular"): {
        "severity": "moderate",
        "effect": "Hyperglycemia — insulin requirements increase dramatically",
        "mechanism": "Corticosteroids cause insulin resistance and gluconeogenesis",
        "recommendation": "increase_insulin_dose_monitor_glucose",
        "safe_alternative": "continue both — adjust insulin doses",
    },
    ("dexamethasone", "metformin"): {
        "severity": "moderate",
        "effect": "Hyperglycemia — metformin may be insufficient",
        "mechanism": "Corticosteroids antagonize metformin's glucose-lowering effect",
        "recommendation": "add_insulin_monitor_glucose",
        "safe_alternative": "switch to insulin during steroid course",
    },
    ("phenobarbital", "warfarin"): {
        "severity": "major",
        "effect": "Reduced warfarin effect — thrombosis risk",
        "mechanism": "Phenobarbital induces CYP2C9 — warfarin degraded faster",
        "recommendation": "increase_warfarin_dose_monitor_inr",
        "safe_alternative": "levetiracetam (no enzyme induction)",
    },
    ("phenobarbital", "phenytoin"): {
        "severity": "moderate",
        "effect": "Unpredictable levels of both drugs",
        "mechanism": "Complex bidirectional CYP induction/inhibition",
        "recommendation": "monitor_levels_of_both",
        "safe_alternative": "levetiracetam instead",
    },
    ("acyclovir", "metformin"): {
        "severity": "moderate",
        "effect": "Increased metformin levels — lactic acidosis risk",
        "mechanism": "Competition for renal tubular secretion",
        "recommendation": "monitor_renal_function",
        "safe_alternative": "switch to insulin",
    },
    ("potassium_chloride", "atenolol"): {
        "severity": "moderate",
        "effect": "Hyperkalemia — beta-blockers mask symptoms",
        "mechanism": "Beta-blockers reduce potassium entry into cells",
        "recommendation": "monitor_potassium_levels",
        "safe_alternative": "use calcium channel blocker instead",
    },
    ("magnesium_sulfate", "calcium_channel_blocker"): {
        "severity": "major",
        "effect": "Profound hypotension and heart block",
        "mechanism": "Magnesium and CCBs both block calcium channels",
        "recommendation": "avoid_combination_monitor_closely",
        "safe_alternative": "labetalol for hypertension in eclampsia",
    },
    ("propofol", "fentanyl"): {
        "severity": "moderate",
        "effect": "Respiratory depression — apnea",
        "mechanism": "Additive CNS and respiratory depression",
        "recommendation": "monitor_respiration_reduce_doses",
        "safe_alternative": "reduce doses of both; ensure airway management ready",
    },
    ("heparin", "aspirin"): {
        "severity": "major",
        "effect": "Significantly increased bleeding risk",
        "mechanism": "Dual antithrombotic effect — anticoagulation + antiplatelet",
        "recommendation": "use_only_when_clinically_indicated",
        "safe_alternative": "use alone unless dual therapy clearly indicated",
    },
    ("insulin_regular", "beta_blocker"): {
        "severity": "moderate",
        "effect": "Masked hypoglycemia symptoms — prolonged hypoglycemia",
        "mechanism": "Beta-blockers block tachycardia and tremor from low glucose",
        "recommendation": "monitor_glucose_closely",
        "safe_alternative": "check glucose frequently; educate on non-adrenergic hypo symptoms",
    },
    ("lisinopril", "nsaid"): {
        "severity": "major",
        "effect": "Acute kidney injury — triple whammy nephrotoxicity",
        "mechanism": "NSAID + ACEi + any diuretic = severe renal hypoperfusion",
        "recommendation": "avoid_nsaids_with_acei",
        "safe_alternative": "acetaminophen for pain",
    },
    ("ondansetron", "amiodarone"): {
        "severity": "major",
        "effect": "Additive QT prolongation — Torsades de Pointes",
        "mechanism": "Both drugs prolong the QT interval",
        "recommendation": "avoid_combination",
        "safe_alternative": "metoclopramide for nausea",
    },
    ("fluoroquinolone", "antacid"): {
        "severity": "moderate",
        "effect": "Reduced antibiotic absorption — treatment failure",
        "mechanism": "Divalent cations chelate fluoroquinolones in GI tract",
        "recommendation": "separate_by_2_hours",
        "safe_alternative": "give ciprofloxacin 2h before or 6h after antacid",
    },
    ("warfarin", "clopidogrel"): {
        "severity": "major",
        "effect": "Extremely high bleeding risk — triple therapy",
        "mechanism": "Three antithrombotic mechanisms simultaneously",
        "recommendation": "minimize_duration_use_ppi_protection",
        "safe_alternative": "consider dual therapy with careful risk-benefit assessment",
    },
    ("vancomycin", "acyclovir"): {
        "severity": "moderate",
        "effect": "Increased nephrotoxicity",
        "mechanism": "Both drugs are nephrotoxic — additive renal tubular damage",
        "recommendation": "monitor_renal_function_daily",
        "safe_alternative": "consider alternative antiviral or reduce vancomycin",
    },
    ("norepinephrine", "maoi"): {
        "severity": "major",
        "effect": "Hypertensive crisis — potentially fatal",
        "mechanism": "MAOIs prevent breakdown of catecholamines — extreme pressor response",
        "recommendation": "avoid_vasopressors_in_maoi_patients",
        "safe_alternative": "phenylephrine (less MAO-dependent) with extreme caution",
    },
    ("furosemide", "lithium"): {
        "severity": "major",
        "effect": "Lithium toxicity — diuresis reduces lithium clearance",
        "mechanism": "Volume depletion causes lithium reabsorption in proximal tubule",
        "recommendation": "monitor_lithium_levels_closely",
        "safe_alternative": "alternative mood stabilizer if possible",
    },
}

DOSE_REFERENCE = {
    "vancomycin": {
        "weight_based": True,
        "dose_mg_per_kg": 15.0,
        "frequency": "q8-12h",
        "renal_adjust": True,
        "notes": "Target AUC/MIC 400-600. Adjust based on levels and renal function.",
    },
    "piperacillin_tazobactam": {
        "weight_based": False,
        "dose_mg": 4500.0,
        "frequency": "q6-8h",
        "renal_adjust": True,
        "notes": "Extended infusion over 4h improves PK/PD target attainment",
    },
    "norepinephrine": {
        "weight_based": True,
        "dose_mcg_per_kg_per_min": 0.1,
        "max_dose": 3.0,
        "titrate": True,
        "notes": "Titrate to MAP > 65 mmHg",
    },
    "insulin_regular": {
        "weight_based": True,
        "dose_units_per_kg": 0.1,
        "target": "glucose 140-180 mg/dL in ICU",
        "notes": "Drip: start at 0.1 units/kg/hr. Adjust q1-2h based on glucose",
    },
    "furosemide": {
        "weight_based": True,
        "dose_mg_per_kg": 0.5,
        "max_single_dose_mg": 200.0,
        "notes": "Double dose if inadequate urine output. Max 200mg IV single dose.",
    },
    "fentanyl": {
        "weight_based": True,
        "dose_mcg_per_kg_per_hr": 25.0,
        "max_dose_mcg_per_kg_per_hr": 200.0,
        "notes": "Preferred opioid in renal failure. Titrate to pain score.",
    },
    "propofol": {
        "weight_based": True,
        "dose_mcg_per_kg_per_min": 25.0,
        "max_dose_mcg_per_kg_per_min": 75.0,
        "notes": "RASS target -1 to -2. Watch for propofol infusion syndrome >48h.",
    },
    "midazolam": {
        "weight_based": True,
        "dose_mg_per_kg": 0.02,
        "max_mg_per_kg": 0.1,
        "notes": "Avoid in renal failure — active metabolite accumulates.",
    },
    "heparin": {
        "weight_based": True,
        "loading_units_per_kg": 80.0,
        "maintenance_units_per_kg_per_hr": 18.0,
        "notes": "Target aPTT 60-100s. Adjust per protocol.",
    },
    "dexamethasone": {
        "weight_based": False,
        "dose_mg": 6.0,
        "frequency": "daily",
        "notes": "COVID-19: 6mg daily for 10 days. Septic shock: 20mg daily.",
    },
}

VITALS_RANGES = {
    "heart_rate": {"normal_min": 60, "normal_max": 100, "critical_low": 40, "critical_high": 140},
    "systolic_bp": {"normal_min": 90, "normal_max": 140, "critical_low": 70, "critical_high": 200},
    "diastolic_bp": {"normal_min": 60, "normal_max": 90, "critical_low": 40, "critical_high": 120},
    "map": {"normal_min": 65, "normal_max": 100, "critical_low": 50, "critical_high": 130},
    "respiratory_rate": {"normal_min": 12, "normal_max": 20, "critical_low": 8, "critical_high": 30},
    "spo2": {"normal_min": 94, "normal_max": 100, "critical_low": 88, "critical_high": 100},
    "temperature": {"normal_min": 36.5, "normal_max": 37.5, "critical_low": 35.0, "critical_high": 40.0},
    "glucose": {"normal_min": 70, "normal_max": 180, "critical_low": 50, "critical_high": 400},
    "creatinine": {"normal_min": 0.6, "normal_max": 1.2, "critical_low": 0.3, "critical_high": 8.0},
    "potassium": {"normal_min": 3.5, "normal_max": 5.0, "critical_low": 2.5, "critical_high": 6.5},
    "sodium": {"normal_min": 135, "normal_max": 145, "critical_low": 120, "critical_high": 160},
    "inr": {"normal_min": 0.8, "normal_max": 1.2, "therapeutic_min": 2.0, "therapeutic_max": 3.0, "critical_high": 5.0},
}

TASK_DRUG_SCENARIOS = {
    "easy": [
        {"drug": "vancomycin", "weight_kg": 70, "condition": "MRSA pneumonia", "correct_dose_mg": 1050.0},
        {"drug": "vancomycin", "weight_kg": 85, "condition": "MRSA bacteremia", "correct_dose_mg": 1275.0},
        {"drug": "vancomycin", "weight_kg": 55, "condition": "MRSA wound infection", "correct_dose_mg": 825.0},
        {"drug": "furosemide", "weight_kg": 80, "condition": "fluid overload", "correct_dose_mg": 40.0},
        {"drug": "furosemide", "weight_kg": 60, "condition": "pulmonary edema", "correct_dose_mg": 30.0},
        {"drug": "acetaminophen", "weight_kg": 75, "condition": "fever", "correct_dose_mg": 1000.0},
        {"drug": "acetaminophen", "weight_kg": 50, "condition": "pain", "correct_dose_mg": 750.0},
        {"drug": "dexamethasone", "weight_kg": 70, "condition": "COVID-19 severe", "correct_dose_mg": 6.0},
        {"drug": "ondansetron", "weight_kg": 70, "condition": "postoperative nausea", "correct_dose_mg": 8.0},
        {"drug": "morphine", "weight_kg": 70, "condition": "acute pain", "correct_dose_mg": 4.0},
    ],
    "medium": [
        {
            "patient": "sepsis patient on warfarin and metoprolol",
            "current_drugs": ["warfarin", "metoprolol", "ciprofloxacin"],
            "dangerous_pair": ("warfarin", "ciprofloxacin"),
            "safe_alternative": "amoxicillin",
        },
        {
            "patient": "heart failure patient",
            "current_drugs": ["digoxin", "furosemide", "amiodarone"],
            "dangerous_pair": ("digoxin", "amiodarone"),
            "safe_alternative": "reduce_digoxin_by_50_percent",
        },
        {
            "patient": "ICU patient with fungal infection",
            "current_drugs": ["warfarin", "fluconazole", "pantoprazole"],
            "dangerous_pair": ("warfarin", "fluconazole"),
            "safe_alternative": "anidulafungin",
        },
        {
            "patient": "patient with atrial fibrillation and delirium",
            "current_drugs": ["amiodarone", "haloperidol", "heparin"],
            "dangerous_pair": ("amiodarone", "haloperidol"),
            "safe_alternative": "quetiapine",
        },
        {
            "patient": "diabetic patient receiving steroids",
            "current_drugs": ["metformin", "dexamethasone", "aspirin"],
            "dangerous_pair": ("metformin", "dexamethasone"),
            "safe_alternative": "insulin_regular",
        },
    ],
}
